export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const MOVIE_REQUEST = 'MOVIE_REQUEST';
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';
export const MOVIE_ERROR = 'MOVIE_ERROR';

export const MOVIES_REQUEST = 'MOVIES_REQUEST';
export const MOVIES_SUCCESS = 'MOVIES_SUCCESS';
export const MOVIES_ERROR = 'MOVIES_ERROR';

export const RECENT_MOVIES_REQUEST = 'RECENT_MOVIES_REQUEST';
export const RECENT_MOVIES_SUCCESS = 'RECENT_MOVIES_SUCCESS';
export const RECENT_MOVIES_ERROR = 'RECENT_MOVIES_ERROR';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
